### PR TITLE
Possible solution to issue #10 

### PR DESCRIPTION
**Pull request by MachineMitch21**
Here is a possible way to do enabling and disabling of systems prompted by fabslabs request.  This way would seperate the disabled systems into their own std::vector.  That way the World wouldn't have to check each system for any kind of disabled flag.  Systems would just be removed from the main systems vector and moved into a disabledSystems vector.  Then they would be removed from disabledSystems and back into the main systems vector upon being enabled again.  Also, not sure about how you'd feel about having registerSystem return the EntitySystem*.  Maybe there's a better way to handle that.

### CODE REVIEW

**Comment by redxdev** [comment]
Looks good to me, but you need to fix indentation to match up with the rest of the project.

**Comment by MachineMitch21** [comment]
This is very strange.  The indentation is fine in all the editors I open up.  It appears to be changing when I push it, though, for some reason.

**Comment by MachineMitch21** [comment]
screenshot 11

**Comment by redxdev** [comment]
Check if you're using tabs while the rest of the project is using spaces (or vice versa, I don't remember off the top of my head what was used). I'd check myself but I won't be able to for a few hours at least.

**Comment by MachineMitch21** [comment]
The problem was that my editor was set for 4 space tabs and you have 8 space tabs.  So it truncated the files down to be 4 space tabs all around.  Everything should be conformant to your indentation now.

**Pull request merged**
